name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ammaraskar/gcc-problem-matcher@master

    - name: deps
      run: sudo apt install libfmt-dev libglm-dev libembree-dev

    - name: configure
      run: cmake
        -DCMAKE_CXX_FLAGS="-O2 -pipe -fno-plt -Wall -Wextra"
        -DCMAKE_C_FLAGS="-O2 -pipe -fno-plt -Wall -Wextra"
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=/usr
        -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
        -B build

    - name: build
      run: |
          export MAKEFLAGS=-j$(nproc)
          cmake --build build

    - name: deb
      run: |
          strip --strip-all $(find build -maxdepth 1 -executable -type f)
          cmake --build build --target package

    - uses: actions/upload-artifact@v3
      with:
        name: ubuntu_package
        path: build/*.deb
